import type { Metadata } from "next";
import { LegalPage, H2, P, Ul, Li, Strong } from "@/components/legal";

export const metadata: Metadata = {
  title: "Disclaimers — DraftEdge",
  description:
    "Important disclaimers regarding DraftEdge's fantasy football tools, data accuracy, trademarks, and liability.",
};

export default function DisclaimersPage() {
  return (
    <LegalPage title="Disclaimers" updated="August 22, 2026">
      <P>
        DraftEdge is a free, open-source fantasy football research and draft
        assistant. The disclaimers below apply to your use of the Service and
        its content. By using DraftEdge, you acknowledge and agree to these
        disclaimers.
      </P>

      {/* ── Fantasy sports ───────────────────────────────── */}
      <H2>Fantasy sports disclaimer</H2>
      <P>
        DraftEdge is a <Strong>research and informational tool</Strong> for
        fantasy football. It is <Strong>not</Strong> a gambling platform, a
        sports betting service, or an operator of real-money contests.
      </P>
      <Ul>
        <Li>
          DraftEdge does not accept, process, or facilitate any wagers, bets,
          or stakes.
        </Li>
        <Li>
          DraftEdge does not host, operate, or manage any fantasy sports contest
          where entry fees are charged or prizes are awarded.
        </Li>
        <Li>
          DraftEdge is not a sportsbook, casino, or any form of gambling
          operator.
        </Li>
      </Ul>

      {/* ── Gambling ──────────────────────────────────────── */}
      <H2>Gambling disclaimer</H2>
      <P>
        All projections, rankings, tiers, trade values, start/sit
        recommendations, and mock draft results are generated by algorithms and
        publicly available data. They are{" "}
        <Strong>estimates for entertainment and informational purposes
        only</Strong> and <Strong>do not guarantee any outcome</Strong>.
      </P>
      <P>
        Nothing in the Service constitutes financial, gambling, investment,
        tax, legal, or professional advice. You are solely responsible for your
        decisions and any consequences arising from them.
      </P>
      <P>
        Fantasy sports laws vary by jurisdiction. Some US states and countries
        restrict or prohibit certain types of fantasy contests. You are
        responsible for determining whether your use of fantasy football tools
        complies with the laws in your jurisdiction.
      </P>
      <P>
        If you or someone you know has a gambling problem, contact the{" "}
        <a
          href="https://www.ncpgambling.org/"
          target="_blank"
          rel="noopener noreferrer"
          className="font-semibold text-emerald-300 hover:underline"
        >
          National Council on Problem Gambling
        </a>{" "}
        at 1-800-522-4700 or text HOME to 741741.
      </P>

      {/* ── Data accuracy ─────────────────────────────────── */}
      <H2>Data accuracy disclaimer</H2>
      <P>
        DraftEdge displays player statistics, projections, rankings, and usage
        metrics sourced from third-party providers. While we strive for
        accuracy, we make no guarantees:
      </P>
      <Ul>
        <Li>
          <Strong>Projections are estimates.</Strong> Player projections are
          algorithmically generated and based on historical data, trends, and
          assumptions. Actual performance will vary due to injuries,
          weather, game script, coaching decisions, and other unpredictable
          factors.
        </Li>
        <Li>
          <Strong>Data may be delayed or incomplete.</Strong> Player data is
          sourced from public APIs (Sleeper, nflverse, FantasyPros) and may
          contain errors, omissions, or delays. Roster moves, injuries, and
          depth chart changes may not be reflected immediately.
        </Li>
        <Li>
          <Strong>No real-time guarantees.</Strong> DraftEdge does not provide
          real-time, live, or in-game data. Projections and rankings reflect
          pre-game expectations and are not updated during live games.
        </Li>
        <Li>
          <Strong>Third-party data dependencies.</Strong> The accuracy and
          availability of data depends on our third-party providers. We are
          not responsible for errors or omissions in their data.
        </Li>
      </Ul>

      {/* ── Payment processing ────────────────────────────── */}
      <H2>Payment processing disclaimer</H2>
      <P>
        DraftEdge is <Strong>entirely free</Strong> and does not process
        payments, handle financial transactions, store payment card data, or
        integrate with any payment processor. DraftEdge does not operate on a
        subscription, freemium, or pay-to-play model.
      </P>
      <P>
        DraftEdge does not comply with the Payment Card Industry Data Security
        Standard (PCI DSS) because no card data is collected, stored,
        processed, or transmitted through the Service. If DraftEdge introduces
        paid features in the future, PCI DSS compliance will be implemented
        through a certified payment processor and this disclaimer will be
        updated.
      </P>

      {/* ── Trademark attribution ────────────────────────── */}
      <H2>Trademark and attribution disclaimer</H2>
      <P>
        DraftEdge is <Strong>not affiliated with, endorsed by, or sponsored
        by</Strong> any of the following organisations:
      </P>
      <Ul>
        <Li>
          National Football League (NFL)
        </Li>
        <Li>
          National Football League Players Association (NFLPA)
        </Li>
        <Li>
          Sleeper Technologies, Inc.
        </Li>
        <Li>
          Yahoo! Inc. / Yahoo Sports
        </Li>
        <Li>
          ESPN / The Walt Disney Company
        </Li>
        <Li>
          FantasyPros
        </Li>
        <Li>
          nflverse
        </Li>
        <Li>
          Any NFL team, NFL player, or collegiate athletic programme
        </Li>
      </Ul>
      <P>
        All team names, player names, logos, uniforms, and related imagery are
        the property of their respective owners and are used here solely for
        informational and identification purposes. The use of any team or
        player name, logo, or mark does not imply endorsement by, or
        association with, any team, player, or league.
      </P>

      {/* ── Open source ────────────────────────────────────── */}
      <H2>Open-source disclaimer</H2>
      <P>
        DraftEdge is open-source software released under the{" "}
        <a
          href="https://opensource.org/licenses/MIT"
          target="_blank"
          rel="noopener noreferrer"
          className="font-semibold text-emerald-300 hover:underline"
        >
          MIT License
        </a>
        . The software is provided &quot;as is&quot; without warranty of any
        kind, as further described in the licence. The DraftEdge name, logo,
        and branding are separate from the open-source code licence and may not
        be used without permission.
      </P>

      {/* ── Third-party links ─────────────────────────────── */}
      <H2>Third-party links disclaimer</H2>
      <P>
        DraftEdge may contain links to third-party websites or services (e.g.
        Supabase, Sleeper, Google). These links are provided for convenience
        only. We do not control, endorse, or assume responsibility for the
        content, privacy policies, or practices of any third-party sites. You
        access third-party links at your own risk.
      </P>

      {/* ── Availability ──────────────────────────────────── */}
      <H2>Service availability disclaimer</H2>
      <P>
        We strive to keep DraftEdge available and error-free, but we make no
        guarantees regarding uptime, availability, or performance. The Service
        may be temporarily unavailable due to maintenance, updates, or factors
        beyond our control. We are not liable for any loss arising from
        downtime or service interruptions.
      </P>

      {/* ── Jurisdiction ───────────────────────────────────── */}
      <H2>Jurisdictional disclaimer</H2>
      <P>
        DraftEdge is operated from the United States and is intended for use
        by users worldwide. However, fantasy sports and data privacy laws vary
        by jurisdiction. It is your responsibility to ensure that your use of
        the Service complies with all applicable laws in your jurisdiction. We
        do not warrant that the Service is legal or available in all
        jurisdictions.
      </P>
    </LegalPage>
  );
}
